name: ${project.name}
main: net.cyberflame.herbs.Main
version: ${project.version}
description: Herbs is a plugin made for Warriors: Far From Home (https://github.com/CyberFlameGO/Herbs/)
website: https://cyberfla.me/
author: CyberFlame (Aaron)
