name: ${project.name}
main: net.cyberflame.herbs.HerbsPlugin
version: ${project.version}
description: Herbs is a plugin made for Warriors Far From Home (https://github.com/CyberFlameGO/Herbs/)
website: https://cyberfla.me/
authors:
  - 'CyberFlame (Aaron)'
  - 'jcrgamer (Edited)'
